title: GuanXiuwei's Homepage
page-top-title: GuanXiuwei
top-section-bg-text: Artificial Intelligence
home-subtitle: GuanXiuwei&ensp;|&ensp;管修为
copyright-text: '&copy; GuanXiuwei2025-2029. All Rights Reserved.'
